# Generated by Django 2.0.6 on 2018-07-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0004_auto_20180629_0130'),
        ('property_management', '0002_auto_20180629_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetail',
            name='Tenant_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuthentication.Tenant'),
        ),
    ]
