# Generated by Django 2.0.6 on 2018-08-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0003_unitdetail_tenant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitdetail',
            old_name='Property_ID',
            new_name='PropertyDetail',
        ),
        migrations.AlterField(
            model_name='propertydetail',
            name='Administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuthentication.Administrator'),
        ),
    ]
