# Generated by Django 2.0.6 on 2018-08-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0004_auto_20180807_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdetail',
            name='Tenant_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuthentication.Tenant'),
        ),
        migrations.AlterField(
            model_name='unitdetail',
            name='Unit_size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
