# Generated by Django 2.0.6 on 2018-06-28 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.CharField(max_length=20)),
                ('City_or_Town', models.CharField(max_length=20)),
                ('Area_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateManagementAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agency_name', models.CharField(max_length=50)),
                ('Phone_number', models.IntegerField()),
                ('Email_address', models.EmailField(max_length=254)),
                ('Website', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdministrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agency_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuthentication.RealEstateManagementAgency')),
                ('User_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='administrator',
            name='Agency_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuthentication.RealEstateManagementAgency'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='User_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
