# Generated by Django 2.0.6 on 2018-06-29 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthentication', '0003_auto_20180629_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatemanagementagency',
            name='Office_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuthentication.Location'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='User_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='User_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='Area_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='City_or_Town',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='County',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='realestatemanagementagency',
            name='Agency_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='realestatemanagementagency',
            name='Email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='realestatemanagementagency',
            name='Phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='realestatemanagementagency',
            name='Website',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='superadministrator',
            name='Agency_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuthentication.RealEstateManagementAgency'),
        ),
        migrations.AlterField(
            model_name='superadministrator',
            name='User_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='User_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
