# Generated by Django 2.1.4 on 2019-01-13 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=20)),
                ('city_or_town', models.CharField(max_length=20)),
                ('area_or_estate_name', models.CharField(blank=True, max_length=20, null=True)),
                ('street_name', models.CharField(blank=True, max_length=20, null=True)),
                ('buiding_nam', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementCompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('physical_address', models.CharField(max_length=20)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('Super-Administrator', 'Super-Administrator'), ('Administrator', 'Administrator')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('occupation', models.CharField(max_length=30)),
                ('relationship_status', models.CharField(max_length=10)),
                ('emergency_contact_name', models.CharField(max_length=50)),
                ('emergency_contact_relationship', models.CharField(max_length=20)),
                ('emergency_contact_phone_number', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantPaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_amount', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('mode_of_payment', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_payment', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('complete payment', 'complete payment'), ('incomplete payment', 'incomplete payment'), ('unpayed', 'unpayed')], max_length=20)),
                ('unit_object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('date_of_exit', models.DateTimeField()),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.TenantDetail')),
                ('unit_contenttype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='tenantpaymentrecord',
            name='tenant_record_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.TenantsRecord'),
        ),
        migrations.AddField(
            model_name='tenantpaymentrecord',
            name='unit_contenttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='extendeduserdetail',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.Role'),
        ),
        migrations.AddField(
            model_name='extendeduserdetail',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
