# Generated by Django 2.1.4 on 2019-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementpersoneldetails',
            name='role',
        ),
        migrations.AddField(
            model_name='managementpersoneldetails',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='managementpersoneldetails',
            name='role_name',
            field=models.CharField(blank=True, choices=[('super-administrator', 'super-administrator'), ('administrator', 'administrator')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('super-administrator', 'super-administrator'), ('administrator', 'administrator')], max_length=20),
        ),
    ]
