# Generated by Django 2.1.4 on 2019-03-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20190324_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='buiding_nam',
            new_name='buiding_name',
        ),
    ]
