# Generated by Django 2.1.4 on 2019-01-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20190116_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsrecord',
            name='date_of_exit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
