# Generated by Django 2.1.4 on 2019-02-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50, null=True)),
                ('property_type', models.CharField(choices=[('Apartments', 'Apartments'), ('Houses', 'Houses'), ('Offices-Bussiness units', 'Offices-Bussiness units')], max_length=50, null=True)),
                ('number_of_units', models.IntegerField(null=True)),
                ('availlable_units', models.IntegerField(null=True)),
                ('occupied_units', models.IntegerField(null=True)),
                ('property_overview_photo', models.FileField(null=True, upload_to='')),
                ('administrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.ManagementPersonelDetails')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.Location')),
                ('management_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.ManagementCompanyDetail')),
            ],
        ),
        migrations.CreateModel(
            name='UnitDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_ID', models.CharField(max_length=10, null=True)),
                ('unit_size', models.CharField(max_length=50, null=True)),
                ('number_of_rooms', models.CharField(max_length=10, null=True)),
                ('unit_value', models.IntegerField(blank=True, null=True)),
                ('unit_purpose', models.CharField(max_length=20, null=True)),
                ('propertyDetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.PropertyDetail')),
                ('tenant_current_month_payment_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.TenantPaymentRecord')),
                ('tenant_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.TenantDetail')),
                ('tenant_records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.TenantsRecord')),
            ],
        ),
        migrations.CreateModel(
            name='UnitPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.FileField(blank=True, null=True, upload_to='')),
                ('unit_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.UnitDetail')),
            ],
        ),
    ]
