# Generated by Django 2.1.4 on 2019-03-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdetail',
            name='unit_ID',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
