# Generated by Django 2.1.4 on 2019-03-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190328_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdetail',
            name='unit_ID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetail',
            name='unit_purpose',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
